# Generated by Django 3.2.7 on 2021-09-20 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 20, 10, 12, 57, 100891, tzinfo=utc)),
        ),
    ]
